/**
 * Every game file baked into this deploy under `public/games/<slug>/<relPath>`,
 * keyed as `<slug>/<relPath>`. The game-serving route consults this set to know a
 * requested asset has a free static twin on the CDN before it redirects there
 * instead of proxying the bytes from Vercel Blob. See
 * {@link chooseGameSource} for how it is used.
 *
 * GENERATED by scripts/build-games-manifest.mjs (runs at prebuild/predev) — do
 * not edit by hand. Regenerated from public/games/ on every build, so it always
 * matches the static files that actually ship.
 */
export const STATIC_GAME_FILES: ReadonlySet<string> = new Set([
  "chroma-orbit/cover.png",
  "chroma-orbit/index.html",
  "color-clash-3d/cover.png",
  "color-clash-3d/index.html",
  "core-vs-swarm/cover.png",
  "core-vs-swarm/index.html",
  "crimson-survivor/cover.png",
  "crimson-survivor/index.html",
  "cube-clash-3d/cover.png",
  "cube-clash-3d/index.html",
  "depths-of-aethelgard/cover.png",
  "depths-of-aethelgard/index.html",
  "duskfall/cover.png",
  "duskfall/index.html",
  "jjk-domain-survival-top-down/cover.png",
  "jjk-domain-survival-top-down/index.html",
  "jjk-domain-survival-v3/cover.png",
  "jjk-domain-survival-v3/index.html",
  "neon-fracture/cover.png",
  "neon-fracture/index.html",
  "neon-hockey/cover.png",
  "neon-hockey/index.html",
  "neon-snake/cover.png",
  "neon-snake/index.html",
  "neon-tether/cover.png",
  "neon-tether/index.html",
  "neon-velocity-hyperdrive/cover.png",
  "neon-velocity-hyperdrive/index.html",
  "neon-well/cover.png",
  "neon-well/index.html",
  "nuclear-reactor-manager/cover.png",
  "nuclear-reactor-manager/index.html",
  "paddle-crawler/cover.png",
  "paddle-crawler/index.html",
  "pixel-bullet-quest/cover.png",
  "pixel-bullet-quest/index.html",
  "pixel-slicer/cover.png",
  "pixel-slicer/index.html",
  "rhythm-hell-harmonic-flash/cover.png",
  "rhythm-hell-harmonic-flash/index.html",
  "sea-mercenary/cover.png",
  "sea-mercenary/index.html",
  "silence/cover.png",
  "silence/index.html",
  "snag/cover.png",
  "snag/index.html",
  "symbiosis/cover.png",
  "symbiosis/index.html",
  "system-error/cover.png",
  "system-error/index.html",
  "system-restore/cover.png",
  "system-restore/index.html",
  "teraria/cover.png",
  "teraria/index.html",
  "vanta-void/cover.png",
  "vanta-void/index.html"
]);
