-- HallPass — the MCP OAuth 2.1 tables (fresh install).
--
-- The canonical DDL for a database being created from scratch. For an EXISTING
-- database, run the one-time `scoreboard/migrations/030_mcp_oauth.sql` instead
-- — the two must stay in lockstep.
--
-- Read that migration's header for the design argument, and
-- `analytics-mcp-design.md` §2 for the whole of it. In brief:
--
--   * These tables are a SECOND credential beside `MCP_SECRET`, not a
--     replacement for it. Either can be unconfigured without disabling the
--     other, and revoking one does not touch the other.
--   * Codes and tokens are stored sha256-hashed and the digest IS the primary
--     key, so a dump of these tables is not a set of live keys.
--   * `email` is the identity and deliberately takes no foreign key —
--     `SUPER_ADMIN_EMAILS` grants a role to an address that may have no
--     `dashboard_users` row, and a key here would lock out exactly the
--     break-glass account.
--   * `grant_id` is what a person calls "a connection": one consent approval,
--     however many tokens, revoked as one thing.

-- Clients register themselves (RFC 7591 dynamic client registration), so this
-- table is written by an UNAUTHENTICATED endpoint. That is what the spec asks
-- for and it is safe on its own — a registration grants nothing until a
-- signed-in dashboard user approves it at the consent screen — but it is also
-- why `/api/oauth/register` rate-limits and why `created_at` is indexed.
CREATE TABLE IF NOT EXISTS mcp_oauth_clients (
  -- Opaque, generated by us. Never guessed from client-supplied metadata.
  client_id     TEXT PRIMARY KEY,
  -- sha256 of the client secret, never the secret. NULL means a PUBLIC client,
  -- which is every self-registered one; a value means a confidential client
  -- created by an admin at /dashboard/mcp for a connector UI that asks for a
  -- secret (Gemini Enterprise's form, for one). Nullable rather than defaulted
  -- to '' on purpose: "no secret" and "the empty secret" must not be the same
  -- value, because the second must never authenticate. See migration 032.
  client_secret_hash TEXT,
  -- The admin email that minted a hand-made client, so a connector nobody
  -- recognises is traceable. NULL for the self-registered ones.
  created_by    TEXT,
  -- What the consent screen shows the human. Client-supplied, so bounded and
  -- rendered as text; a client that sends nothing gets a generic label rather
  -- than an empty heading.
  client_name   TEXT NOT NULL CHECK (length(client_name) BETWEEN 1 AND 120),
  -- EXACT-MATCH allow-list. The authorize endpoint compares the incoming
  -- redirect_uri against these strings and refuses anything else, which is the
  -- single control that stops an authorization code being handed to somebody
  -- else's URL. Capped because an unbounded list is a free-form redirector.
  redirect_uris TEXT[] NOT NULL
                  CHECK (cardinality(redirect_uris) BETWEEN 1 AND 10),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_used_at  TIMESTAMPTZ
);

-- Registration rate limiting counts rows in a window; without this it is a
-- sequential scan on the one table an unauthenticated caller can grow.
CREATE INDEX IF NOT EXISTS mcp_oauth_clients_created_idx
  ON mcp_oauth_clients (created_at DESC);

-- One row per authorization code. Single-use and short-lived: the token
-- endpoint redeems by UPDATE ... WHERE consumed_at IS NULL AND expires_at >
-- now(), so a replayed code matches nothing and is refused rather than
-- re-issuing a token.
CREATE TABLE IF NOT EXISTS mcp_oauth_codes (
  code_hash      TEXT PRIMARY KEY,
  client_id      TEXT NOT NULL
                   REFERENCES mcp_oauth_clients (client_id) ON DELETE CASCADE,
  email          TEXT NOT NULL,
  player_id      TEXT,
  -- Pinned at issue and re-checked at redemption: RFC 6749 requires the token
  -- request's redirect_uri to match the one the code was issued against, or a
  -- code intercepted at one registered URI could be redeemed against another.
  redirect_uri   TEXT NOT NULL,
  -- PKCE S256 only. `plain` is refused in the application layer rather than
  -- stored and compared, so there is no column recording which method was used
  -- — there is only one.
  code_challenge TEXT NOT NULL CHECK (length(code_challenge) BETWEEN 43 AND 128),
  scope          TEXT NOT NULL,
  -- The audience the eventual token is for. The MCP spec REQUIRES a server to
  -- refuse tokens not issued for itself, so the resource is carried from the
  -- authorization request all the way onto the token row.
  resource       TEXT NOT NULL,
  expires_at     TIMESTAMPTZ NOT NULL,
  consumed_at    TIMESTAMPTZ,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The sweep in the writer's CTE deletes by age.
CREATE INDEX IF NOT EXISTS mcp_oauth_codes_expiry_idx
  ON mcp_oauth_codes (expires_at);

CREATE TABLE IF NOT EXISTS mcp_oauth_tokens (
  token_hash   TEXT PRIMARY KEY,
  kind         TEXT NOT NULL CHECK (kind IN ('access','refresh')),
  -- See the header: one approval, one grant_id, however many tokens.
  grant_id     UUID NOT NULL,
  client_id    TEXT NOT NULL
                 REFERENCES mcp_oauth_clients (client_id) ON DELETE CASCADE,
  email        TEXT NOT NULL,
  player_id    TEXT,
  scope        TEXT NOT NULL,
  resource     TEXT NOT NULL,
  expires_at   TIMESTAMPTZ NOT NULL,
  -- Set rather than deleted, so a revoked token stays refused for as long as
  -- the row lives instead of becoming an unknown token the sweep might race.
  revoked_at   TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- What `/dashboard/mcp` shows as "last used", and the only reason the
  -- per-request lookup writes anything at all.
  last_used_at TIMESTAMPTZ
);

-- Revoking a connection updates the whole family at once.
CREATE INDEX IF NOT EXISTS mcp_oauth_tokens_grant_idx
  ON mcp_oauth_tokens (grant_id);

-- `/dashboard/mcp` lists one person's connections, newest first.
CREATE INDEX IF NOT EXISTS mcp_oauth_tokens_email_idx
  ON mcp_oauth_tokens (email, created_at DESC);

-- The sweep in the writer's CTE deletes by age.
CREATE INDEX IF NOT EXISTS mcp_oauth_tokens_expiry_idx
  ON mcp_oauth_tokens (expires_at);
