-- HallPass — migration: OAuth 2.1 for the MCP endpoint.
--
-- See `app/lib/mcp/oauth/schema.sql` for the canonical fresh-install DDL; keep
-- the two in lockstep. `analytics-mcp-design.md` §2 is the full argument.
--
-- ── WHY THIS EXISTS ─────────────────────────────────────────────────────────
-- `/api/mcp` has been reachable with one shared `MCP_SECRET` since it shipped,
-- and `bug-mcp-design.md` §2 argued that was the honest shape of "one person
-- holds one key". These three tables are the second credential beside it: an
-- OAuth 2.1 authorization server, so an MCP client can sign in with the same
-- Google account that opens the dashboard. The secret is untouched; the two
-- paths are independent and either can be unconfigured without the other.
--
-- ── EVERYTHING SECRET IS STORED HASHED, NEVER IN THE CLEAR ──────────────────
-- Authorization codes and tokens are 32 random bytes; what is stored is their
-- sha256, and the primary key IS that digest. A lookup hashes what was
-- presented and finds the row, so a dump of these tables is not a set of live
-- keys. Same reasoning `admin-secret.ts` already applies to the shared secrets,
-- and the reason the columns are named `*_hash` rather than `code`/`token`.
--
-- ── EMAIL IS THE IDENTITY, AND IS DELIBERATELY NOT A FOREIGN KEY ────────────
-- A grant belongs to an email, because that is what `dashboard_users` is keyed
-- on and what the role ladder is resolved against. It is NOT
-- `REFERENCES dashboard_users(email)`: `SUPER_ADMIN_EMAILS` grants
-- `super_admin` unconditionally to an address that may have no row at all
-- (see `role-seats-design.md`), so a foreign key here would make the break-glass
-- account the one account that cannot connect. The role is re-resolved per
-- request anyway, so a stale row grants nothing.
--
-- `player_id` is carried for the activity feed only and likewise takes no key.
--
-- ── grant_id IS WHAT THE DASHBOARD CALLS A "CONNECTION" ─────────────────────
-- One approval at the consent screen mints an access token and a refresh token,
-- and every rotation of that refresh mints more. A person thinks of all of that
-- as one thing — "Claude Code is connected" — and revokes it as one thing. The
-- shared `grant_id` is that thing: revoking a connection is one UPDATE over the
-- family, and `/dashboard/mcp` lists grants rather than tokens.
--
-- ── RETENTION IS BY AGE, IN THE WRITER'S OWN STATEMENT ──────────────────────
-- Codes live 60 seconds and tokens expire; nothing else would ever remove them.
-- `oauth/store.ts` sweeps expired rows from a data-modifying CTE on the writes
-- that already touch these tables, keeping it one round trip — the neon() HTTP
-- driver is one stateless request per call, so two statements would not be one
-- transaction anyway. Same pattern as `beta_agent_activity`.
--
-- Fully idempotent — every statement guarded, whole file in one transaction.

BEGIN;

-- Clients register themselves (RFC 7591 dynamic client registration), so this
-- table is written by an UNAUTHENTICATED endpoint. That is what the spec asks
-- for and it is safe on its own — a registration grants nothing until a
-- signed-in dashboard user approves it at the consent screen — but it is also
-- why `/api/oauth/register` rate-limits and why `created_at` is indexed.
CREATE TABLE IF NOT EXISTS mcp_oauth_clients (
  -- Opaque, generated by us. Never guessed from client-supplied metadata.
  client_id     TEXT PRIMARY KEY,
  -- What the consent screen shows the human. Client-supplied, so bounded and
  -- rendered as text; a client that sends nothing gets a generic label rather
  -- than an empty heading.
  client_name   TEXT NOT NULL CHECK (length(client_name) BETWEEN 1 AND 120),
  -- EXACT-MATCH allow-list. The authorize endpoint compares the incoming
  -- redirect_uri against these strings and refuses anything else, which is the
  -- single control that stops an authorization code being handed to somebody
  -- else's URL. Capped because an unbounded list is a free-form redirector.
  redirect_uris TEXT[] NOT NULL
                  CHECK (cardinality(redirect_uris) BETWEEN 1 AND 10),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_used_at  TIMESTAMPTZ
);

-- Registration rate limiting counts rows in a window; without this it is a
-- sequential scan on the one table an unauthenticated caller can grow.
CREATE INDEX IF NOT EXISTS mcp_oauth_clients_created_idx
  ON mcp_oauth_clients (created_at DESC);

-- One row per authorization code. Single-use and short-lived: the token
-- endpoint redeems by UPDATE ... WHERE consumed_at IS NULL AND expires_at >
-- now(), so a replayed code matches nothing and is refused rather than
-- re-issuing a token.
CREATE TABLE IF NOT EXISTS mcp_oauth_codes (
  code_hash      TEXT PRIMARY KEY,
  client_id      TEXT NOT NULL
                   REFERENCES mcp_oauth_clients (client_id) ON DELETE CASCADE,
  email          TEXT NOT NULL,
  player_id      TEXT,
  -- Pinned at issue and re-checked at redemption: RFC 6749 requires the token
  -- request's redirect_uri to match the one the code was issued against, or a
  -- code intercepted at one registered URI could be redeemed against another.
  redirect_uri   TEXT NOT NULL,
  -- PKCE S256 only. `plain` is refused in the application layer rather than
  -- stored and compared, so there is no column recording which method was used
  -- — there is only one.
  code_challenge TEXT NOT NULL CHECK (length(code_challenge) BETWEEN 43 AND 128),
  scope          TEXT NOT NULL,
  -- The audience the eventual token is for. The MCP spec REQUIRES a server to
  -- refuse tokens not issued for itself, so the resource is carried from the
  -- authorization request all the way onto the token row.
  resource       TEXT NOT NULL,
  expires_at     TIMESTAMPTZ NOT NULL,
  consumed_at    TIMESTAMPTZ,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The sweep in the writer's CTE deletes by age.
CREATE INDEX IF NOT EXISTS mcp_oauth_codes_expiry_idx
  ON mcp_oauth_codes (expires_at);

CREATE TABLE IF NOT EXISTS mcp_oauth_tokens (
  token_hash   TEXT PRIMARY KEY,
  kind         TEXT NOT NULL CHECK (kind IN ('access','refresh')),
  -- See the header: one approval, one grant_id, however many tokens.
  grant_id     UUID NOT NULL,
  client_id    TEXT NOT NULL
                 REFERENCES mcp_oauth_clients (client_id) ON DELETE CASCADE,
  email        TEXT NOT NULL,
  player_id    TEXT,
  scope        TEXT NOT NULL,
  resource     TEXT NOT NULL,
  expires_at   TIMESTAMPTZ NOT NULL,
  -- Set rather than deleted, so a revoked token stays refused for as long as
  -- the row lives instead of becoming an unknown token the sweep might race.
  revoked_at   TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- What `/dashboard/mcp` shows as "last used", and the only reason the
  -- per-request lookup writes anything at all.
  last_used_at TIMESTAMPTZ
);

-- Revoking a connection updates the whole family at once.
CREATE INDEX IF NOT EXISTS mcp_oauth_tokens_grant_idx
  ON mcp_oauth_tokens (grant_id);

-- `/dashboard/mcp` lists one person's connections, newest first.
CREATE INDEX IF NOT EXISTS mcp_oauth_tokens_email_idx
  ON mcp_oauth_tokens (email, created_at DESC);

-- The sweep in the writer's CTE deletes by age.
CREATE INDEX IF NOT EXISTS mcp_oauth_tokens_expiry_idx
  ON mcp_oauth_tokens (expires_at);

COMMIT;
