/**
 * HallPass — the game-invites store (factory).
 *
 * Same seam as `challenges/store.ts` and `p2p/store.ts`: the factory takes the
 * tagged-template `sql`, so this module stays free of `server-only` and the
 * fake-`sql` tests can assert the shape of every statement; `index.ts` binds the
 * live Neon client. Codes are PARAMETERS, generated by the caller, so the
 * factory stays free of `crypto` and tests deterministically.
 *
 * ── ONE STATEMENT PER OPERATION, forced by the driver ──────────────────────
 * `neon()` is SQL-over-HTTP: a `BEGIN` here and a `COMMIT` there are not one
 * transaction. Every gate below — friendship, block, cooldown, staged
 * visibility, the sender's rate limit — is therefore evaluated in the SAME
 * statement as the insert it guards, against one snapshot. A block checked in a
 * separate round trip is a block that can be raced by the write it is meant to
 * stop. The rate limit is best-effort under true concurrency (two simultaneous
 * requests can both see a count under the cap), the trade every limiter in this
 * codebase accepts.
 *
 * ── NO CRON ────────────────────────────────────────────────────────────────
 * Each WRITE also deletes rows that expired more than `GC_GRACE_SECONDS` ago,
 * in a data-modifying CTE that Postgres runs whether or not the main query reads
 * it. Reads never write. The grace is what keeps the hourly limits honest.
 *
 * ── NAMES ──────────────────────────────────────────────────────────────────
 * Every name that leaves here is the PUBLIC display name — handle, else
 * `@username`, else "Player". The Google `name` is never selected: it is most
 * people's real name, and these names land in somebody else's notification and
 * on a page built to be pasted into a group chat. No avatar is selected for the
 * landing page for the same reason (`challenge-sharing-design.md` §7); the
 * picker's own friend list carries `image` exactly as `listFriends` does,
 * because it is the player's own friends shown to the player.
 *
 * ── NEVER PUT A BARE PARAMETER CASE INSIDE make_interval() ─────────────────
 * See `challenges/store.ts`: every `make_interval` below takes exactly one bare
 * parameter, which is the shape that resolves.
 */

import type { NeonQueryFunction } from "@neondatabase/serverless";
import type { PublicProfile } from "@/app/lib/social/store";
import {
  FRIEND_INVITE_RATE_LIMIT,
  GC_GRACE_SECONDS,
  INVITE_PAIR_COOLDOWN_SECONDS,
  type InviteKind,
  type RateLimit,
} from "./config";

type Sql = NeonQueryFunction<false, false>;
type Row = Record<string, unknown>;

/** `count(*)` and BIGINT arrive from the HTTP driver as strings. */
function toInt(value: unknown): number {
  const n = Number(value);
  return Number.isFinite(n) ? n : 0;
}

function toIso(value: unknown): string {
  const date = new Date(value as string);
  return Number.isNaN(date.getTime()) ? String(value) : date.toISOString();
}

/**
 * Handle, else `@username`, else "Player" — `publicDisplayName`'s rule,
 * reproduced rather than imported to keep the factory free of `players.ts`
 * (which binds the live `sql`), exactly as `challenges/store.ts` does.
 */
function displayNameFrom(handle: unknown, username: unknown): string {
  const h = handle == null ? null : String(handle).trim();
  const u = username == null ? null : String(username);
  return h || (u ? `@${u}` : "Player");
}

/** JSONB arrives parsed from the driver; tolerate a string anyway. */
function toObject(value: unknown): Record<string, unknown> {
  let v = value;
  if (typeof v === "string") {
    try {
      v = JSON.parse(v);
    } catch {
      return {};
    }
  }
  return v && typeof v === "object" && !Array.isArray(v) ? (v as Record<string, unknown>) : {};
}

/** A friend as the picker shows them. */
export type InvitableFriend = PublicProfile & {
  /** Already invited by this player to this game inside the cooldown. */
  invitedRecently: boolean;
};

/** Who was invited, as internal ids — these stay server-side (who to notify). */
export type SentInvite = { toId: string; code: string };

/** Everything `createFriendInvites` learned, whether or not it wrote rows. */
export type FriendInviteOutcome = {
  sent: SentInvite[];
  /** Recipients that passed every per-recipient gate. */
  eligible: number;
  /** Friend invites this sender already made inside the window. */
  recent: number;
  /** The batch would have crossed the hourly limit, so nothing was written. */
  rateLimited: boolean;
  /** The sender's public display name, for the notification. */
  fromDisplayName: string;
};

/** What `createLink` learned. */
export type LinkOutcome = { code: string | null; rateLimited: boolean };

/** An invite as `/i/<code>` sees it. */
export type PublicInvite = {
  code: string;
  slug: string;
  kind: InviteKind;
  data: Record<string, unknown>;
  /** The inviter's public display name; `null` for a guest's link. */
  from: string | null;
  expiresAt: string;
  /** Judged by the DATABASE clock, so a skewed server clock cannot revive one. */
  expired: boolean;
  /** Whole seconds until it expires, by the same clock; `0` once expired. */
  secondsLeft: number;
};

export function createInviteStore(sql: Sql) {
  return {
    /**
     * The player's friends who can receive an invite to `slug`: accepted, not
     * blocked either way and — for a staged game — able to see staged games (an
     * active beta tester, or a dashboard role by `dashboard_users` or the
     * `SUPER_ADMIN_EMAILS` list, which is `canViewStaged()`'s rule applied to
     * somebody other than the caller). Newest friend first, like `listFriends`.
     */
    async listInvitableFriends(input: {
      me: string;
      slug: string;
      stagedOnly: boolean;
      adminEmails: string[];
    }): Promise<InvitableFriend[]> {
      const { me, slug, stagedOnly, adminEmails } = input;
      const rows = (await sql`
        SELECT p.public_id, p.username, p.handle, p.image,
               EXISTS (
                 SELECT 1 FROM game_invites g
                  WHERE g.from_player = ${me}
                    AND g.kind = 'friend'
                    AND g.to_player = p.id
                    AND g.slug = ${slug}
                    AND g.created_at >= now() - make_interval(secs => ${INVITE_PAIR_COOLDOWN_SECONDS})
               ) AS invited_recently
          FROM friendships f
          JOIN players p
            ON p.id = CASE WHEN f.player_a = ${me} THEN f.player_b ELSE f.player_a END
         WHERE f.status = 'accepted'
           AND (f.player_a = ${me} OR f.player_b = ${me})
           AND NOT EXISTS (
                 SELECT 1 FROM player_blocks b
                  WHERE (b.blocker_id = ${me} AND b.blocked_id = p.id)
                     OR (b.blocker_id = p.id AND b.blocked_id = ${me})
               )
           AND (
                 NOT ${stagedOnly}::boolean
                 OR EXISTS (
                      SELECT 1 FROM beta_testers bt
                       WHERE bt.player_id = p.id AND bt.revoked_at IS NULL
                    )
                 OR lower(p.email) IN (SELECT lower(d.email) FROM dashboard_users d)
                 OR lower(p.email) = ANY(${adminEmails}::text[])
               )
         ORDER BY f.responded_at DESC NULLS LAST, f.created_at DESC
      `) as Row[];
      return rows.map((row) => ({
        id: String(row.public_id),
        username: row.username == null ? null : String(row.username),
        displayName: displayNameFrom(row.handle, row.username),
        image: row.image == null ? null : String(row.image),
        invitedRecently: row.invited_recently === true,
      }));
    },

    /**
     * Invite friends to a game — one row per recipient, one statement.
     *
     * Recipients arrive as PUBLIC ids and are resolved here, so an unknown id
     * simply produces no candidate. Each candidate must pass, against one
     * snapshot: accepted friendship (either stored direction — compared both
     * ways rather than through `LEAST`/`GREATEST`, which would depend on the
     * column collation `friendships_ordered_chk` pins), no block either way, no
     * invite from this sender to them for this game inside the cooldown, and
     * the staged-visibility rule when `stagedOnly`.
     *
     * THE RATE LIMIT IS ALL-OR-NOTHING. If this batch would carry the sender
     * past the hourly allowance, nothing is written and `rateLimited` says so.
     * Half a batch, silently chosen, would be a worse thing to explain than
     * "try fewer friends or wait".
     *
     * `codes` is positional with `toPublicIds` (same length).
     */
    async createFriendInvites(input: {
      senderId: string;
      slug: string;
      json: string;
      toPublicIds: string[];
      codes: string[];
      ttlSeconds: number;
      stagedOnly: boolean;
      adminEmails: string[];
    }): Promise<FriendInviteOutcome> {
      const { senderId, slug, json, toPublicIds, codes, ttlSeconds, stagedOnly, adminEmails } = input;
      const { maxPerWindow, windowSeconds } = FRIEND_INVITE_RATE_LIMIT;
      const rows = (await sql`
        WITH gc AS (
          DELETE FROM game_invites
           WHERE expires_at < now() - make_interval(secs => ${GC_GRACE_SECONDS})
        ),
        sender AS (
          SELECT handle, username FROM players WHERE id = ${senderId}
        ),
        cand AS (
          SELECT p.id, p.email, t.code, t.ord
            FROM unnest(${toPublicIds}::uuid[], ${codes}::text[])
                 WITH ORDINALITY AS t(public_id, code, ord)
            JOIN players p ON p.public_id = t.public_id
           WHERE p.id <> ${senderId}
        ),
        eligible AS (
          SELECT c.id, c.code, c.ord
            FROM cand c
           WHERE EXISTS (
                   SELECT 1 FROM friendships f
                    WHERE f.status = 'accepted'
                      AND ((f.player_a = ${senderId} AND f.player_b = c.id)
                        OR (f.player_a = c.id AND f.player_b = ${senderId}))
                 )
             AND NOT EXISTS (
                   SELECT 1 FROM player_blocks b
                    WHERE (b.blocker_id = ${senderId} AND b.blocked_id = c.id)
                       OR (b.blocker_id = c.id AND b.blocked_id = ${senderId})
                 )
             AND NOT EXISTS (
                   SELECT 1 FROM game_invites g
                    WHERE g.from_player = ${senderId}
                      AND g.kind = 'friend'
                      AND g.to_player = c.id
                      AND g.slug = ${slug}
                      AND g.created_at >= now() - make_interval(secs => ${INVITE_PAIR_COOLDOWN_SECONDS})
                 )
             AND (
                   NOT ${stagedOnly}::boolean
                   OR EXISTS (
                        SELECT 1 FROM beta_testers bt
                         WHERE bt.player_id = c.id AND bt.revoked_at IS NULL
                      )
                   OR lower(c.email) IN (SELECT lower(d.email) FROM dashboard_users d)
                   OR lower(c.email) = ANY(${adminEmails}::text[])
                 )
        ),
        recent AS (
          SELECT count(*) AS n FROM game_invites
           WHERE from_player = ${senderId}
             AND kind = 'friend'
             AND created_at >= now() - make_interval(secs => ${windowSeconds})
        ),
        ins AS (
          INSERT INTO game_invites (code, slug, kind, data, from_player, to_player, expires_at)
          SELECT e.code, ${slug}, 'friend', ${json}::jsonb, ${senderId}, e.id,
                 now() + make_interval(secs => ${ttlSeconds})
            FROM eligible e
           WHERE (SELECT n FROM recent) + (SELECT count(*) FROM eligible) <= ${maxPerWindow}
           ORDER BY e.ord
          ON CONFLICT (code) DO NOTHING
          RETURNING to_player, code
        )
        SELECT COALESCE(
                 (SELECT json_agg(json_build_object('to', i.to_player, 'code', i.code)) FROM ins i),
                 '[]'::json
               )                                  AS sent,
               (SELECT count(*) FROM eligible)    AS eligible_n,
               (SELECT n FROM recent)             AS recent_n,
               (SELECT handle FROM sender)        AS from_handle,
               (SELECT username FROM sender)      AS from_username
      `) as Row[];

      const row = rows[0] ?? {};
      const raw = Array.isArray(row.sent) ? (row.sent as Row[]) : [];
      const eligible = toInt(row.eligible_n);
      const recent = toInt(row.recent_n);
      return {
        sent: raw.map((r) => ({ toId: String(r.to), code: String(r.code) })),
        eligible,
        recent,
        rateLimited: eligible > 0 && recent + eligible > maxPerWindow,
        fromDisplayName: displayNameFrom(row.from_handle, row.from_username),
      };
    },

    /**
     * Make one share link. A signed-in player's links are counted by their id;
     * a guest's by `senderKey`, the salted IP hash, which is stored on the row
     * for exactly that and nothing else. Exactly one of the two is non-null.
     *
     * `code` is `null` when the limit refused it (or, practically never, when the
     * code collided — the caller treats both as "try again").
     */
    async createLink(input: {
      senderId: string | null;
      senderKey: string | null;
      slug: string;
      json: string;
      code: string;
      ttlSeconds: number;
      limit: RateLimit;
    }): Promise<LinkOutcome> {
      const { senderId, senderKey, slug, json, code, ttlSeconds, limit } = input;
      const rows = (await sql`
        WITH gc AS (
          DELETE FROM game_invites
           WHERE expires_at < now() - make_interval(secs => ${GC_GRACE_SECONDS})
        ),
        recent AS (
          SELECT count(*) AS n FROM game_invites
           WHERE kind = 'link'
             AND created_at >= now() - make_interval(secs => ${limit.windowSeconds})
             AND (from_player = ${senderId}
                  OR (from_player IS NULL AND sender_key = ${senderKey}))
        ),
        ins AS (
          INSERT INTO game_invites (code, slug, kind, data, from_player, sender_key, expires_at)
          SELECT ${code}, ${slug}, 'link', ${json}::jsonb, ${senderId}, ${senderKey},
                 now() + make_interval(secs => ${ttlSeconds})
           WHERE (SELECT n FROM recent) < ${limit.maxPerWindow}
          ON CONFLICT (code) DO NOTHING
          RETURNING code
        )
        SELECT (SELECT code FROM ins) AS code,
               (SELECT n FROM recent) AS recent_n
      `) as Row[];
      const row = rows[0] ?? {};
      return {
        code: row.code == null ? null : String(row.code),
        rateLimited: toInt(row.recent_n) >= limit.maxPerWindow,
      };
    },

    /**
     * The `/i/<code>` read. `null` when no such row exists. An EXPIRED row is
     * returned with `expired: true` so the page can still offer the game; a row
     * past the GC grace has simply gone, which reads the same as never existing.
     */
    async getByCode(code: string): Promise<PublicInvite | null> {
      const rows = (await sql`
        SELECT g.code, g.slug, g.kind, g.data, g.expires_at,
               (g.expires_at <= now())       AS expired,
               GREATEST(0, floor(EXTRACT(EPOCH FROM (g.expires_at - now()))))::int AS seconds_left,
               (g.from_player IS NOT NULL)   AS has_sender,
               p.handle AS from_handle, p.username AS from_username
          FROM game_invites g
          LEFT JOIN players p ON p.id = g.from_player
         WHERE g.code = ${code}
         LIMIT 1
      `) as Row[];
      const row = rows[0];
      if (!row) return null;
      return {
        code: String(row.code),
        slug: String(row.slug),
        kind: String(row.kind) === "link" ? "link" : "friend",
        data: toObject(row.data),
        from: row.has_sender === true ? displayNameFrom(row.from_handle, row.from_username) : null,
        expiresAt: toIso(row.expires_at),
        expired: row.expired === true,
        secondsLeft: toInt(row.seconds_left),
      };
    },
  };
}

export type InviteStore = ReturnType<typeof createInviteStore>;
